### ISSUE TITLE
'Creating first pod' example raises error

### ISSUE THREAD

**Issue by njf0** [uoe-eidf-cluster-users/eidf-epcc-cluster#26]
I'm working through the 'creating your first pod' part of the README (`https://github.com/uoe-eidf-cluster-users/eidf-epcc-cluster#run-a-pod`), using the `.yml` file below.

```yaml
apiVersion: v1
kind: Pod
metadata:
 generateName: first-pod-
spec:
 restartPolicy: OnFailure
 containers:
  - name: cudasample
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1
    args: ["-benchmark", "-numbodies=512000", "-fp64", "-fullscreen"]
    resources:
     limits:
       nvidia.com/gpu: 1
```

After running `kubectl create -f test_NBody.yml`, I get the error
```
Error from server (Forbidden): error when creating "test_NBody.yml": admission webhook "validation.gatekeeper.sh" denied the request: [userpodlimits] container <cudasample> has no cpu limit, please see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
[userpodlimits] container <cudasample> has no memory limit, please see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
```
I understand that the message requires additional resource limits, and have attempted to supply them according to the website in the message, however, I then receive an error
```
Error from server (Forbidden): error when creating "test_NBody.yml": pods "sample-7w6fz" is forbidden: exceeded quota: informatics-compute-resources, requested: limits.cpu=1,requests.nvidia.com/gpu=1, used: limits.cpu=1724,requests.nvidia.com/gpu=60, limited: limits.cpu=1400,requests.nvidia.com/gpu=60
```
Aim of this is to complete the example/tutorial and for the example to be updated if necessary. Thanks.
